wordpress:
    image: wordpress:latest
    links:
        - wp_db:mysql
    volumes:
        - ./wordpress/wp-content:/var/www/html/wp-content
    ports:
        - 8080:80
wp_db:
    image: mysql:latest
    volumes:
        - db_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: supersecretpassword

phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
        - wp_db:mysql
    ports:
        - 8181:80
    environment:
        PMA_HOST: mysql
